"""Removida a coluna cpf da tabela de profissionais

Revision ID: 4776a72b5d78
Revises: 8b45bc536c2b
Create Date: 2025-08-17 16:46:05.102095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4776a72b5d78'
down_revision = '8b45bc536c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_index('ix_profissionais_cpf')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=True))
        batch_op.create_index('ix_profissionais_cpf', ['cpf'], unique=True)

    # ### end Alembic commands ###
