"""Initial tables

Revision ID: 562f77653d1e
Revises: 
Create Date: 2025-08-27 03:38:59.282854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562f77653d1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('valor_mensal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dias_carencia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=True),
    sa.Column('empresa', sa.String(length=128), nullable=True),
    sa.Column('url_foto', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('status_assinatura', sa.String(length=64), nullable=True),
    sa.Column('data_fim_carencia', sa.DateTime(), nullable=True),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('portarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_portaria', sa.String(length=256), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('apartamento', sa.String(length=32), nullable=True),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('portaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['portaria_id'], ['portarias.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['referred_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_referral_code'), ['referral_code'], unique=True)

    op.create_table('acessos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('servico', sa.String(length=256), nullable=True),
    sa.Column('empresa', sa.String(length=256), nullable=True),
    sa.Column('tipo_acesso', sa.String(length=15), nullable=True),
    sa.Column('observacoes_morador', sa.Text(), nullable=True),
    sa.Column('data_prevista_acesso', sa.Date(), nullable=True),
    sa.Column('data_acesso', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('usuario_morador_id', sa.Integer(), nullable=True),
    sa.Column('usuario_porteiro_id', sa.Integer(), nullable=True),
    sa.Column('portaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['portaria_id'], ['portarias.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['usuario_morador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_porteiro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acessos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_referral_code'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('portarias')
    op.drop_table('condominios')
    op.drop_table('profissionais')
    op.drop_table('planos')
    # ### end Alembic commands ###
