"""Adicionado profissional_id e campos de indicacao ao User

Revision ID: 8b45bc536c2b
Revises: d2b514a009de
Create Date: 2025-08-15 20:45:47.579587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b45bc536c2b'
down_revision = 'd2b514a009de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acessos', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('servico',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('empresa',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_constraint('acessos_porteiro_saida_id_fkey', type_='foreignkey')
        batch_op.drop_column('porteiro_saida_id')

    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_foto', sa.String(length=256), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               nullable=True)
        batch_op.drop_constraint('profissionais_cpf_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_profissionais_cpf'), ['cpf'], unique=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profissional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key(None, 'usuarios', ['referred_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'profissionais', ['profissional_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usuarios_referral_code'))
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('profissional_id')

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profissionais_cpf'))
        batch_op.create_unique_constraint('profissionais_cpf_key', ['cpf'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.drop_column('url_foto')

    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    with op.batch_alter_table('acessos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porteiro_saida_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('acessos_porteiro_saida_id_fkey', 'usuarios', ['porteiro_saida_id'], ['id'])
        batch_op.alter_column('empresa',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('servico',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
