"""Adiciona coluna tipo_acesso à tabela acesso

Revision ID: c23293562df4
Revises: 4776a72b5d78
Create Date: 2025-08-17 20:01:30.226653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23293562df4'
down_revision = '4776a72b5d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acessos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_acesso', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acessos', schema=None) as batch_op:
        batch_op.drop_column('tipo_acesso')

    # ### end Alembic commands ###
