"""Adiciona campos empresa e url_foto ao modelo Profissional

Revision ID: d2b514a009de
Revises: 
Create Date: 2025-08-14 21:01:48.031739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b514a009de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('url_foto', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('url_foto')
        batch_op.drop_column('empresa')

    # ### end Alembic commands ###
