"""Adicionar tabelas de Portaria e atualizar relações

Revision ID: fbb07af43c6a
Revises: c23293562df4
Create Date: 2025-08-18 02:07:06.788539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb07af43c6a'
down_revision = 'c23293562df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acessos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portaria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'portarias', ['portaria_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portaria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'portarias', ['portaria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portaria_id')

    with op.batch_alter_table('acessos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portaria_id')

    op.drop_table('portarias')
    # ### end Alembic commands ###
